# **Import des modules nécessaires**

In [ ]:
import pandas as pd #pour la manipulation de données
from pathlib import Path #pour la gestion des chemins de fichiers

from bertopic import BERTopic #pour la modélisation de sujets

from umap import UMAP #pour la réduction de dimensionnalité

from sklearn.cluster import KMeans #pour le clustering
from hdbscan import HDBSCAN #pour le clustering de BERTopic

from sklearn.feature_extraction.text import CountVectorizer #pour la vectorisation de texte
from bertopic.vectorizers import ClassTfidfTransformer #pour la vectorisation de texte spécifique à BERTopic

from sentence_transformers import SentenceTransformer #pour les embeddings de phrases

# **Chargement du corpus de Zola**

In [69]:
df=pd.read_csv(Path("..") /"data" /"2_processed"/ "02_corpus_zola.csv", encoding="utf-8",)
df.head()

,roman,annee,ordre_romans,paquet_id,texte,nb_mots
0,1865 La confession de Claude.,1865,1,1,"Voici l’hiver: l’air, au matin, devient plus f...",985
1,1865 La confession de Claude.,1865,1,2,"Ai-je eu trop de confiance en ma force, ma pla...",1067
2,1865 La confession de Claude.,1865,1,3,Hélas! il me faut cependant une ombre de réali...,894
3,1865 La confession de Claude.,1865,1,4,Elle dormait. J’ai entassé sur ses pieds tous ...,1158
4,1865 La confession de Claude.,1865,1,5,"Ainsi, jamais mon cœur ne pourra battre sans q...",1027

In [70]:
df.shape

(3556, 6)

# **Traitement du Corpus de Zola**

## **1) Choix du modèle d'embedding**

Ici je vais choisir un modèle d'embedding pré-entraîné pour transformer les textes en vecteurs numériques. Je vais utiliser un modèle de la bibliothèque Sentence Transformers, qui est compatible avec BERTopic.

In [71]:
embedding_model = SentenceTransformer(
    "sentence-transformers/distiluse-base-multilingual-cased-v2"
)

Loading weights:   0%|          | 0/100 [00:00<?, ?it/s]

## **2) Pipeline de Traitement**

In [72]:
docs = df["texte"].tolist()

timestamps = df["ordre_romans"].tolist()

### 1) UMAP

In [85]:
umap_model = UMAP(
    n_neighbors=10,
    n_components=10,
    min_dist=1,
    metric="cosine",
    random_state=42
)

### 2) HDBSCAN

In [ ]:
hdbscan_model = HDBSCAN(
    min_cluster_size=15,
    min_samples=1,
    metric="euclidean",
    cluster_selection_method="leaf",
    prediction_data=True
)

In [74]:
cluster_model = KMeans(
    n_clusters=15,
    random_state=42,
    n_init="auto"

)

### 3) creation des stop words + vectorisation TF-IDF

In [75]:
stop_word = [
    # Rougon / Macquart / noms familiaux centraux
    "rougon", "macquart", "saccard", "mouret", "lantier", "coupeau", "maheu", "fouan", "quenu", "chanteau", "josserand", "deberle",
    "raquin", "lorilleux", "buteau", "roubaud", "baudu", "gervaise",

    # Prénoms / personnages très fréquents
    "pierre", "jean", "jacques", "marie", "madeleine", "pauline", "hélène", "jeanne", "claude", "marius", "lazare", "guillaume",
    "laurent", "philippe", "thérèse", "albine", "maurice", "marthe", "maxime", "daniel", "camille", "serge", "octave", "florent",
    "félicité", "louise", "silvère", "caroline", "lisa", "laurence", "miette", "simon", "josine", "clotilde", "véronique", "juliette",
    "rosalie", "mathieu", "charles", "françoise", "lise", "séverine", "henriette", "georges", "angélique", "adèle", "pascal", "lucie", 
    "martine", "virginie", "suzanne", "valentine", "olympe", "lucien", "armande", "constance", "berthe", "sidonie", "benedetta",

    # Noms propres / personnages complémentaires
    "luc", "geneviève", "catherine", "chaval", "adélaïde", "antoine", "auguste", "marianne", "clorinde", "normande", "saget", "mlle saget",
    "delhomme", "ragu", "trouche", "sandoz", "mahoudeau", "bonneville", "rastoil", "rambaud", "fenil", "surin", "malignon", "faloise",
    "lambesc", "mignot", "baugé", "morange", "bouchard", "teuse", "pâquerette", "paquerette", "duparque", "mme duparque", "guersaint",
    "aurélie", "aurelie", "mme aurélie", "mme aurelie", "lecœur", "lecoeur", "mme lecœur", "mme lecoeur", "granoux", "bourron",
    "lerat", "mme lerat", "duveyrier", "bachelard", "gueulin", "delaherche", "beauclair", "lison", "orlando", "delbos",
    "boisgelin", "fernande", "sébastien", "sebastien", "mazaud", "dubuche", "moreux", "vigneron", "bourrette", "satan",
    "archangias", "férat", "ferat", "barbue", "trouille", "laveuve",

    # Personnages secondaires / noms très discriminants
    "fauchery", "muffat", "bordenave", "zoé", "mignon", "faujas", "mathéus", "trublot", "fagerolles", "cazalis", "poizat", "jordan",
    "vandeuvres", "condamin", "paloque", "charbonnel", "gilquin", "marjolin", "campardon", "toussaint", "grivet", "denizet", "kahn",
    "hutin", "bonnaire", "laboque", "marsy", "nanet", "favier", "deloche", "goujet", "cadine", "chouteau", "rochas", "lepailleur",
    "séguin", "gagnière", "hourdequin", "macqueron", "théodose", "savin", "gérard", "larsonneau", "morfain", "lorin", "salvat",
    "boche", "gavard", "martelly",

    # Groupes nominaux religieux / institutionnels
    "sœur hyacinthe", "soeur hyacinthe", "mère chantemesse", "mere chantemesse",

     # Formes d’adresse / famille
    "monsieur", "madame", "mademoiselle", "mme", "mlle",
    "maman", "papa", "père", "pere", "mère", "mere",
    "frère", "frere", "frères", "freres", "sœur", "soeur",
    "sœurette", "soeurette", "tante", "oncle", "cousin",
    "cousine", "époux", "epoux", "épouse", "epouse",
    "nièce", "niece",

    # Mots très fréquents et peu informatifs
    "le", "la", "les", "un", "une", "des", "du", "de", "d", "au", "aux",
    "ce", "cet", "cette", "ces", "son", "sa", "ses", "leur", "leurs",
    "je", "tu", "il", "elle", "nous", "vous", "ils", "elles",
    "me", "te", "se", "moi", "toi", "lui", "eux",
    "que", "qui", "quoi", "dont", "où", "et", "ou", "mais", "donc",
    "or", "ni", "car", "ne", "pas", "plus", "moins", "très",
    "dans", "sur", "sous", "avec", "sans", "pour", "par", "comme",
    "chez", "vers", "entre", "contre", "depuis", "pendant",
    "tout", "tous", "toute", "toutes", "même", "autre", "autres",
    "être", "avoir", "faire", "dire", "aller", "voir", "savoir",
    "pouvoir", "vouloir", "falloir", "devoir", "venir", "prendre",
    "mettre", "donner", "trouver", "passer", "rester", "sembler",
    "encore", "toujours", "jamais", "bien", "mal", "peu", "assez",
    "alors", "puis", "enfin", "aussi", "ainsi", "déjà", "là",
    "ici", "cela", "ça", "ceci", "celui", "celle", "ceux", "celles"
]

In [90]:
vectorizer_model = CountVectorizer(
    stop_words=stop_word,
    min_df=3,
    max_df=0.90
)

ctfidf_model = ClassTfidfTransformer(
    reduce_frequent_words=True
)

### 4) Création du modèle BERTopic

In [91]:
topic_model = BERTopic(
    embedding_model=embedding_model,
    umap_model=umap_model,
    #hdbscan_model=cluster_model,
    vectorizer_model=vectorizer_model,
    language="multilingual",
    calculate_probabilities=False,
    verbose=True
)

topics, probs = topic_model.fit_transform(docs)

df["topic"] = topics

2026-06-02 16:55:37,715 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/112 [00:00<?, ?it/s]

2026-06-02 16:56:00,635 - BERTopic - Embedding - Completed ✓
2026-06-02 16:56:00,637 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-06-02 16:56:10,657 - BERTopic - Dimensionality - Completed ✓
2026-06-02 16:56:10,659 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-06-02 16:56:10,843 - BERTopic - Cluster - Completed ✓
2026-06-02 16:56:10,847 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-06-02 16:56:12,065 - BERTopic - Representation - Completed ✓

## **3) Topics Présent**

In [93]:
topic_info = topic_model.get_topic_info()
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,1968,-1_abbé_saint_bruit_docteur,"[abbé, saint, bruit, docteur, marc, bête, prêt...","[La montée était longue, des quartiers surgiss..."
1,0,1511,0_abbé_saint_église_bruit,"[abbé, saint, église, bruit, prêtre, rouge, fo...","[En face de l’entrée, à la place ordinaire de ..."
2,1,40,1_nana_fontan_lucy_comte,"[nana, fontan, lucy, comte, labordette, satin,...",[Les hommes qui se plantaient devant les affic...
3,2,22,2_fine_joseph_barricades_armateur,"[fine, joseph, barricades, armateur, marseille...",[Le comte s’établit sur le palier du troisième...
4,3,15,3_chantebled_moulin_docteur_nicolas,"[chantebled, moulin, docteur, nicolas, santerr...","[Ensuite, par rang de générations, les autres ..."

In [ ]:
for topic_id in topic_info["Topic"].head(15):
    if topic_id != -1:
        print("\nTOPIC", topic_id)
        print(topic_model.get_topic(topic_id)[:15])

TOPIC 0
[('millions', np.float64(0.004175623079363673)), ('bourse', np.float64(0.004089654832029945)), ('cent mille', np.float64(0.0033575832726324547)), ('cents francs', np.float64(0.0033106341423296617)), ('capital', np.float64(0.0031461236697110967)), ('cinquante', np.float64(0.0028821650804342607)), ('actions', np.float64(0.00281238609143753)), ('payer', np.float64(0.0027351951819240663)), ('ouvriers', np.float64(0.0026400789745479342)), ('hérédité', np.float64(0.002627439136523141))]

TOPIC 1
[('général', np.float64(0.00864733267784234)), ('troupes', np.float64(0.007183862267088316)), ('armée', np.float64(0.006955321928697617)), ('soldats', np.float64(0.006361377991876613)), ('sedan', np.float64(0.006191676842745636)), ('canon', np.float64(0.005818917370790989)), ('insurgés', np.float64(0.005368156016708426)), ('drapeau', np.float64(0.004782319807285889)), ('bazeilles', np.float64(0.004744506236714055)), ('ducrot', np.float64(0.004634195697380423))]

TOPIC 2
[('amant', np.float64(0.0055813048526496345)), ('affection', np.float64(0.0035938892301601165)), ('marc', np.float64(0.003442214914824146)), ('baisers', np.float64(0.0034291641136677186)), ('blessures', np.float64(0.0032994279134330555)), ('souffrances', np.float64(0.0032753663571700184)), ('pensées', np.float64(0.003200949961770982)), ('pensait', np.float64(0.003102487775472473)), ('dormait', np.float64(0.002994609818745927)), ('noiraude', np.float64(0.002972174484102283))]

TOPIC 3
[('nana', np.float64(0.007715044151792136)), ('comte', np.float64(0.006209993941338544)), ('vénus', np.float64(0.004702417702058023)), ('mon cher', np.float64(0.0037170854253325506)), ('comtesse', np.float64(0.003371831227985296)), ('clarisse', np.float64(0.0032453971142919987)), ('public', np.float64(0.0031668531084130835)), ('steiner', np.float64(0.002939770911846365)), ('aperçu', np.float64(0.0029317623019359286)), ('diane', np.float64(0.0028303147347410614))]

TOPIC 4
[('morceau', np.float64(0.005285325171504823)), ('vin', np.float64(0.004086737337267738)), ('plat', np.float64(0.003791027291064931)), ('fromage', np.float64(0.003260665951640896)), ('estomac', np.float64(0.003135522221430051)), ('poisson', np.float64(0.0031072477606943548)), ('mangé', np.float64(0.0030998381120949593)), ('servante', np.float64(0.0030613287478682724)), ('dessert', np.float64(0.0030043356631803265)), ('poêle', np.float64(0.002979316877463074))]

TOPIC 5
[('curé', np.float64(0.010643105063251092)), ('évêque', np.float64(0.00682484424539664)), ('saint saturnin', np.float64(0.0064859258106581925)), ('soutane', np.float64(0.006301597994972932)), ('maffre', np.float64(0.006077946276171713)), ('saturnin', np.float64(0.005905821069499648)), ('vierge', np.float64(0.005880196861743278)), ('volant', np.float64(0.005737199021920214)), ('plassans', np.float64(0.005370327914483281)), ('monseigneur', np.float64(0.005351901867331713))]

TOPIC 6
[('docteur', np.float64(0.01010180382972193)), ('henri', np.float64(0.004075533155446181)), ('denise', np.float64(0.0038436929358308452)), ('cazenove', np.float64(0.0036999963678277835)), ('médecin', np.float64(0.0033891695777714744)), ('mer', np.float64(0.0032707536009271942)), ('algues', np.float64(0.003146919614810596)), ('horteur', np.float64(0.0030426385389163806)), ('abbé horteur', np.float64(0.0030426385389163806)), ('paul', np.float64(0.0028412142514584993))]

TOPIC 7
[('marc', np.float64(0.004032014217181039)), ('hyacinthe', np.float64(0.0031482122600622955)), ('sainte', np.float64(0.00314602194941297)), ('victor', np.float64(0.003082235087419809)), ('alice', np.float64(0.003047482990677557)), ('vierge', np.float64(0.0030222579527171087)), ('école', np.float64(0.0028035661273450242)), ('malades', np.float64(0.0027202146813699924)), ('voyage', np.float64(0.00268659457844496)), ('bernadette', np.float64(0.00260379632427443))]

TOPIC 8
[('bourse', np.float64(0.0038971909091146503)), ('ernesta', np.float64(0.0037580730070379043)), ('sœurs', np.float64(0.0036937591056645583)), ('colomban', np.float64(0.0034783684270267823)), ('poisson', np.float64(0.0034253814367712263)), ('jory', np.float64(0.0033543196429797048)), ('morceaux', np.float64(0.003179038289053184)), ('bonjour', np.float64(0.0031718429272561788)), ('potager', np.float64(0.0031596603720414848)), ('cassis', np.float64(0.0030738181324407705))]

TOPIC 9
[('halles', np.float64(0.004956782692623442)), ('aristide', np.float64(0.0034299579156760514)), ('veau', np.float64(0.00341756341200491)), ('zéphyrin', np.float64(0.0032957605776568607)), ('étienne', np.float64(0.003129400770878965)), ('bonnemort', np.float64(0.0031238433524055334)), ('aurions', np.float64(0.0030032852180679093)), ('forgeron', np.float64(0.00271316329642756)), ('delestang', np.float64(0.002697871787297445)), ('hautecœur', np.float64(0.0026792183923255823))]

TOPIC 10
[('plafond', np.float64(0.003299873280560111)), ('rideaux', np.float64(0.0030245750362182383)), ('armoire', np.float64(0.0029380267662346077)), ('veilleuse', np.float64(0.002926651819915561)), ('papier', np.float64(0.0028952289651461537)), ('renée', np.float64(0.002879933814307587)), ('lueur', np.float64(0.0028739132225042547)), ('mon ami', np.float64(0.002818572910332343)), ('élisabeth', np.float64(0.0027912844027670708)), ('rébufat', np.float64(0.0027558547779140755))]

TOPIC 11
[('république', np.float64(0.006286517051821784)), ('nationale', np.float64(0.006081727553856405)), ('gouvernement', np.float64(0.00545906525294181)), ('prussiens', np.float64(0.004849152497998719)), ('garde nationale', np.float64(0.004687346180387083)), ('vengeance', np.float64(0.004085605874159968)), ('armée', np.float64(0.003916550780687967)), ('école', np.float64(0.0037809056360308567)), ('berlin', np.float64(0.003547295967979547)), ('réaction', np.float64(0.003469519553659337))]

TOPIC 12
[('prussiens', np.float64(0.009853899476286137)), ('général', np.float64(0.008446328563968269)), ('armée', np.float64(0.006893067230317587)), ('soldats', np.float64(0.006786028608813479)), ('camp', np.float64(0.006467627081874421)), ('meuse', np.float64(0.006230278100783639)), ('fusil', np.float64(0.005639317822723354)), ('fouchard', np.float64(0.00527101129430236)), ('obus', np.float64(0.005209612899716827)), ('loubet', np.float64(0.004984222480626911))]

TOPIC 13
[('renée', np.float64(0.009076944365582113)), ('janzen', np.float64(0.0036854271393527553)), ('hubertine', np.float64(0.003583360214207367)), ('bassin', np.float64(0.0033650496188725775)), ('feuilles', np.float64(0.0031990675982804563)), ('mareuil', np.float64(0.0031772642203991316)), ('princesse', np.float64(0.0030121594319123353)), ('isnard', np.float64(0.003010487500623922)), ('amants', np.float64(0.0028605037918359786)), ('préfet', np.float64(0.0028208460178911795))]