# **Import des modules nécessaires**

In [94]:
import pandas as pd #pour la manipulation de données
from pathlib import Path #pour la gestion des chemins de fichiers
import spacy #pour le prétraitement de texte
from spacy.lang.fr.stop_words import STOP_WORDS as spacy_stopwords

from bertopic import BERTopic #pour la modélisation de sujets

from umap import UMAP #pour la réduction de dimensionnalité
from hdbscan import HDBSCAN #pour le clustering de BERTopic
from sklearn.cluster import KMeans #pour le clustering de BERTopic

from sklearn.feature_extraction.text import CountVectorizer #pour la vectorisation de texte
from bertopic.vectorizers import ClassTfidfTransformer #pour la vectorisation de texte spécifique à BERTopic

from sentence_transformers import SentenceTransformer #pour les embeddings de phrases

# **Chargement du corpus de Zola et de spacy**

In [69]:
df=pd.read_csv(Path("..") /"data" /"2_processed"/ "02_corpus_zola.csv", encoding="utf-8",)
df.head()

,roman,annee,ordre_romans,paquet_id,texte,nb_mots
0,1865 La confession de Claude.,1865,1,1,"Voici l’hiver: l’air, au matin, devient plus f...",401
1,1865 La confession de Claude.,1865,1,2,Le grillon chantait; le souffle harmonieux des...,336
2,1865 La confession de Claude.,1865,1,3,"Pars cependant, puisque tu as soif de la vie. ...",248
3,1865 La confession de Claude.,1865,1,4,"Ai-je eu trop de confiance en ma force, ma pla...",336
4,1865 La confession de Claude.,1865,1,5,Le premier rayon a chassé le cauchemar de ma v...,359

In [70]:
df.shape

(10638, 6)

# **Traitement du Corpus de Zola**

In [71]:
# Chargement du modèle avec désactivation du 'parser' syntaxique pour gagner en vitesse
# On garde impérativement 'ner' pour repérer les personnages/lieux et 'lemmatizer'
nlp = spacy.load("fr_core_news_lg", disable=["parser"])
nlp.max_length = 2_000_000  

#on convertit en liste
textes_bruts = df["texte"].astype(str).tolist()

textes_nettoyes = []

# Utilisation de nlp.pipe pour traiter les textes par blocs (très rapide)
for doc in nlp.pipe(textes_bruts, batch_size=50): 
    tokens = [] # Liste pour stocker les tokens nettoyés
    
    for token in doc:
        lemme = token.lemma_.lower() # Obtenir le lemme du token en minuscules
        
        if (
            not token.is_stop # Ignorer les stop words spaCy par défaut
            and not token.is_punct # Ignorer la ponctuation
            and not token.like_num # Ignorer les chiffres
            and not token.is_space # Ignorer les espaces vides
            and token.ent_type_ not in ['PER', 'LOC', 'ORG'] # Ignorer les Personnages, Lieux et Organisations
            and token.pos_ in {"NOUN", "ADJ", "VERB"}  # Garder Noms, Adjectifs ET Verbes
            and len(lemme) > 2 # Ignorer les mots de 1 ou 2 lettres
        ):
            tokens.append(lemme)
            
    # Rejoindre les tokens validés et les ajouter à la liste finale
    textes_nettoyes.append(" ".join(tokens))

# Application de la liste nettoyée à la nouvelle colonne du DataFrame
df["phrases_lemm"] = textes_nettoyes

# Affichage du résultat
df[["phrases_lemm"]].head()

                                        phrases_lemm
0  hiver air matin devenir frais mettre manteau b...
1  grillon chanter souffle harmonieux nuit bercer...
2  soif vie projet soi ferme loyal action rêve vi...
3  confiance force place rêver côté jour naître p...
4  rayon chasser cauchemar veille obstacle accept...

## **1) Choix du modèle d'embedding**

Ici je vais choisir un modèle d'embedding pré-entraîné pour transformer les textes en vecteurs numériques. Je vais utiliser un modèle de la bibliothèque Sentence Transformers, qui est compatible avec BERTopic.

In [72]:
embedding_model = SentenceTransformer(
    "dangvantuan/sentence-camembert-base"
)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

In [73]:
print("Génération des embeddings sémantiques...")
embeddings = embedding_model.encode(df['texte'].tolist(), show_progress_bar=True)

Génération des embeddings sémantiques...

Batches:   0%|          | 0/333 [00:00<?, ?it/s]

## **2) Pipeline de Traitement**

### 1) HDBSCAN et UMAP

In [117]:
#hdbscan_model = HDBSCAN( min_cluster_size=40, min_samples=2, metric='euclidean', cluster_selection_method='eom',prediction_data=True)

cluster_model = KMeans(n_clusters=30, 
                       random_state=42)

umap_model = UMAP( n_neighbors=20,n_components=8, min_dist=0.0, metric="cosine",random_state=42)

### 2) creation des stop words + vectorisation TF-IDF

In [118]:
stop_perso=[
    "grand", "petit", "homme", "femme", "jour", "heure", "coup", "œil", 
    "main", "bras", "tête", "voix", "milieu", "eau", "terre", "air", "monde", 
    "chose", "nuit", "vie", "enfant", "père", "mère", "fille", "garçon", 
    "monsieur", "madame", "falloir", "aller", "voir", "dire", "faire", 
    "pouvoir", "vouloir", "savoir", "venir", "devoir", "prendre", "donner",
    "oui", "non", "où", "quand", "comment", "deberl", "coupeau", "men", "hein", 
    "tape", "liard", "mercredi"
]

stop_word = list(spacy_stopwords) + stop_perso

### 3) CountVectorizer et ClassTfidfTransformer avec des stop words personnalisés

In [136]:
vectorizer_model = CountVectorizer(
    stop_words=stop_word,
    min_df=12, #
    max_df=0.40 #   
)

ctfidf_model = ClassTfidfTransformer(
    reduce_frequent_words=True,
)


topic_model = BERTopic(
    language="french",
    hdbscan_model=cluster_model,
    umap_model=umap_model,
    vectorizer_model=vectorizer_model,
    ctfidf_model=ctfidf_model,
    calculate_probabilities=False,
    verbose=True
)
topics, probs = topic_model.fit_transform(df["phrases_lemm"].tolist(), embeddings= embeddings)

2026-06-04 10:58:05,821 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-06-04 10:58:15,765 - BERTopic - Dimensionality - Completed ✓
2026-06-04 10:58:15,767 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-06-04 10:58:15,796 - BERTopic - Cluster - Completed ✓
2026-06-04 10:58:15,799 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-06-04 10:58:16,640 - BERTopic - Representation - Completed ✓

## **3) Topics Présent**

In [137]:
topic_info = topic_model.get_topic_info()
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,0,554,0_collectiviste_harmonie_historique_ensemencer,"[collectiviste, harmonie, historique, ensemenc...",[anarchie venir fondre évolution communiste ré...
1,1,546,1_portique_encensoir_oranger_estrade,"[portique, encensoir, oranger, estrade, symbol...",[évoquer savoir splendeur basilique déborder f...
2,2,511,2_phase_impur_tâtonnant_brutaliser,"[phase, impur, tâtonnant, brutaliser, salutair...",[face gonflé oeil doux front limpide disparaît...
3,3,469,3_décret_brusquer_gale_clinique,"[décret, brusquer, gale, clinique, mange, médi...",[intéressant intéressant répéter monsieur reme...
4,4,430,4_flocon_épine_impur_dodo,"[flocon, épine, impur, dodo, réconfort, sépulc...",[demande avorter jeter pierre somme bon action...
5,5,427,5_fagot_tapissier_polisson_sevrer,"[fagot, tapissier, polisson, sevrer, dégrafer,...",[grand table déjeuner bel appétit servir tour ...
6,6,422,6_accusé_expert_paraphe_auditoire,"[accusé, expert, paraphe, auditoire, beaumonta...",[entendre modèle reconnaître venir timbrer par...
7,7,412,7_pudique_insatiable_délai_épine,"[pudique, insatiable, délai, épine, impur, avo...",[fontaine sceller sanctuaire reposer trône cit...
8,8,400,8_prune_saucisse_cochonnerie_soûler,"[prune, saucisse, cochonnerie, soûler, jus, es...",[jour cochon homme poisson quartier mépriser e...
9,9,395,9_crève_cochonnerie_charbonner_décrasser,"[crève, cochonnerie, charbonner, décrasser, fr...",[mourir soir compagnon essayer mâcher feuille ...
10,10,386,10_présentation_remisier_candidature_exceptionnel,"[présentation, remisier, candidature, exceptio...",[succès bruit disparition journal courir semai...
11,11,371,11_créance_intermédiaire_candidature_auréole,"[créance, intermédiaire, candidature, auréole,...",[occuper étage grand maison neuf propriétaire ...
12,12,364,12_cavalerie_escouade_marseillais_boucherie,"[cavalerie, escouade, marseillais, boucherie, ...",[gauche étageaient vallonnement venir voir pet...
13,13,351,13_levier_galibot_cuve_réverbération,"[levier, galibot, cuve, réverbération, bretell...",[revenir recette vol géant tête grelotter cour...
14,14,348,14_calorifère_réseau_grog_niaiserie,"[calorifère, réseau, grog, niaiserie, salutair...",[penser roulure sembler mauvais gale crever ad...
15,15,342,15_galet_dodo_citron_crânerie,"[galet, dodo, citron, crânerie, pouls, louve, ...",[porte retourner maheude clouer chaise oublier...
16,16,325,16_cicatrice_agile_conseilla_vis,"[cicatrice, agile, conseilla, vis, brutaliser,...",[doute homme vouloir étouffer cri perdre sauve...
17,17,323,17_indemnité_prélever_émission_expropriation,"[indemnité, prélever, émission, expropriation,...",[ancien irrégularité aggraver système consiste...
18,18,315,18_herse_diocèse_pie_bracelet,"[herse, diocèse, pie, bracelet, ravissant, rev...",[chose faire finir prévenir envoyer mot heure ...
19,19,311,19_navet_fur_citron_esquisse,"[navet, fur, citron, esquisse, bilan, barreau,...",[associer vente petit tas promettre sou jour v...
20,20,309,20_diligence_percepteur_réclamation_substitut,"[diligence, percepteur, réclamation, substitut...",[jour marquis petit tête aristocratique arrive...
21,21,303,21_forçat_sucrerie_mathématique_indolent,"[forçat, sucrerie, mathématique, indolent, inf...",[vie accepter vie aimer fonction peur saluer c...
22,22,303,22_leste_brodeuse_sénile_manifester,"[leste, brodeuse, sénile, manifester, incondui...",[éclater larme premier mot explication prêtre ...
23,23,296,23_spéculer_décrasser_informer_dramatique,"[spéculer, décrasser, informer, dramatique, bo...",[blanc étrangler révolte inconcevable mari dir...
24,24,260,24_trimestre_bilan_grog_rythmique,"[trimestre, bilan, grog, rythmique, réclamatio...",[vivre personne compter franc père autant jete...
25,25,260,25_pouls_impotent_substitut_expier,"[pouls, impotent, substitut, expier, fraude, t...",[laisser voir entendre songer chose calmer pos...
26,26,258,26_coiffée_mat_rosace_ébouriffer,"[coiffée, mat, rosace, ébouriffer, ravissant, ...",[attendre demi-heure croire sortir voir soleil...
27,27,241,27_cicatrice_crêpe_défoncé_perquisition,"[cicatrice, crêpe, défoncé, perquisition, caba...",[enfant avoir rire clair écouter histoire père...
28,28,203,28_animation_éponger_identité_percevoir,"[animation, éponger, identité, percevoir, ento...",[suite sentir regarder travers lamentable aban...
29,29,203,29_boyau_laveuse_graisser_bretelle,"[boyau, laveuse, graisser, bretelle, galibot, ...",[propre gêner air scandaliser paraître furieux...

In [138]:
# Récupération de la dimension temporelle
timestamps = df['annee'].tolist()

# Génération des topics dans le temps
topics_over_time = topic_model.topics_over_time(
    df['phrases_lemm'].tolist(), 
    timestamps, 
    nr_bins=20 # Optionnel : à ajuster selon le nombre d'années distinctes de ton corpus
)

# Visualisation interactive de l'évolution des 10 premiers topics
topic_model.visualize_topics_over_time(topics_over_time, top_n_topics=10)

19it [00:01, 14.99it/s]

In [ ]:
for topic_id in topic_info["Topic"].head(15):
    if topic_id != -1:
        print("\nTOPIC", topic_id)
        print(topic_model.get_topic(topic_id)[:15])

TOPIC 0
[('grand', np.float64(0.017005147472741993)), ('petit', np.float64(0.014208018885504065)), ('milieu', np.float64(0.011649919335881862)), ('heure', np.float64(0.011448751791126012)), ('homme', np.float64(0.011340309172830763)), ('haut', np.float64(0.011135275125658681)), ('coup', np.float64(0.010420100248090423)), ('jour', np.float64(0.010374217810644532)), ('noir', np.float64(0.010220925988676414)), ('terre', np.float64(0.010133559609535362))]

TOPIC 1
[('heure', np.float64(0.01590057452709807)), ('vie', np.float64(0.015721006039242803)), ('femme', np.float64(0.015695122366292842)), ('jour', np.float64(0.015297611576967926)), ('grand', np.float64(0.015239284874121461)), ('amour', np.float64(0.014666138576746177)), ('enfant', np.float64(0.014664660828043958)), ('petit', np.float64(0.013150656817104542)), ('oeil', np.float64(0.013114889067034027)), ('cœur', np.float64(0.01302664749795748))]

TOPIC 2
[('vie', np.float64(0.020569552224391538)), ('cœur', np.float64(0.01979860439510658)), ('femme', np.float64(0.018149941878155558)), ('enfant', np.float64(0.018046307888821177)), ('amour', np.float64(0.01797689112246276)), ('grand', np.float64(0.01584013832965367)), ('main', np.float64(0.015613825599527184)), ('oeil', np.float64(0.01551010555436325)), ('bras', np.float64(0.01529932665773193)), ('fille', np.float64(0.015145543165751478))]

TOPIC 3
[('grand', np.float64(0.017045260445183005)), ('homme', np.float64(0.01620377820369495)), ('petit', np.float64(0.012549309433582841)), ('frère', np.float64(0.012427112292680464)), ('affaire', np.float64(0.012354846448519051)), ('jour', np.float64(0.012036085499894931)), ('bon', np.float64(0.012010975962981748)), ('père', np.float64(0.010736150961037803)), ('heure', np.float64(0.010653158928685439)), ('coup', np.float64(0.010400802904890526))]

TOPIC 4
[('petit', np.float64(0.01780668525923642)), ('bon', np.float64(0.016131670875690483)), ('femme', np.float64(0.0153583400066645)), ('coup', np.float64(0.014387049138173156)), ('jour', np.float64(0.014143552515820357)), ('heure', np.float64(0.01375027462922693)), ('grand', np.float64(0.013426649464333393)), ('homme', np.float64(0.013277657726526367)), ('air', np.float64(0.013099618981258818)), ('monsieur', np.float64(0.012418824945560307))]

TOPIC 5
[('monsieur', np.float64(0.023050258944065996)), ('homme', np.float64(0.018296159024436758)), ('abbé', np.float64(0.017669696904696337)), ('grand', np.float64(0.015989506538976957)), ('petit', np.float64(0.015050363634288445)), ('heure', np.float64(0.014888549037314382)), ('bon', np.float64(0.013975231360054784)), ('air', np.float64(0.013919546472835498)), ('prêtre', np.float64(0.013890365295019294)), ('main', np.float64(0.013391123519328443))]

TOPIC 6
[('peuple', np.float64(0.018662664519312453)), ('grand', np.float64(0.016168040425159656)), ('homme', np.float64(0.01455150533687117)), ('travail', np.float64(0.014324943047308724)), ('jour', np.float64(0.014315088981037326)), ('monde', np.float64(0.014166085332009897)), ('terre', np.float64(0.01312347351470553)), ('vie', np.float64(0.01255449256614713)), ('science', np.float64(0.011743819218616149)), ('enfant', np.float64(0.011625788688837088))]

TOPIC 7
[('main', np.float64(0.020940409784498015)), ('oeil', np.float64(0.01806721182723792)), ('bras', np.float64(0.017941055394460472)), ('tête', np.float64(0.01780295674677441)), ('coup', np.float64(0.0172222664514397)), ('sang', np.float64(0.014929188615482288)), ('petit', np.float64(0.014924744427797294)), ('femme', np.float64(0.014002982328182579)), ('grand', np.float64(0.013318552562185702)), ('pied', np.float64(0.013238850885470074))]

TOPIC 8
[('franc', np.float64(0.024497369024459113)), ('monsieur', np.float64(0.024165186407108685)), ('argent', np.float64(0.01950425031987429)), ('femme', np.float64(0.018843720872838525)), ('homme', np.float64(0.017964843280548374)), ('bon', np.float64(0.01796111925852408)), ('chose', np.float64(0.014019014699888595)), ('jour', np.float64(0.013516170865880556)), ('petit', np.float64(0.01340414384862645)), ('fille', np.float64(0.013210876227655441))]

TOPIC 9
[('femme', np.float64(0.02057695854485135)), ('monsieur', np.float64(0.020261200626337794)), ('petit', np.float64(0.019680413519843263)), ('jeune', np.float64(0.017338742077036774)), ('dame', np.float64(0.01714767104107791)), ('air', np.float64(0.015953789210650292)), ('fille', np.float64(0.01587084795352853)), ('bon', np.float64(0.015694431981626542)), ('grand', np.float64(0.015578833562939922)), ('oeil', np.float64(0.014949067298793129))]

TOPIC 10
[('franc', np.float64(0.026428598840240035)), ('grand', np.float64(0.016867078261952412)), ('jour', np.float64(0.015516461948186469)), ('petit', np.float64(0.014791619038572046)), ('maison', np.float64(0.014435485190634749)), ('argent', np.float64(0.014203566300130708)), ('homme', np.float64(0.014096990909573458)), ('fortune', np.float64(0.013754767815483286)), ('père', np.float64(0.012997994437815064)), ('bon', np.float64(0.012506741632719488))]

TOPIC 11
[('chambre', np.float64(0.02369491801457157)), ('lit', np.float64(0.02083026029647309)), ('porte', np.float64(0.018632618898756597)), ('heure', np.float64(0.01773464322786477)), ('petit', np.float64(0.017336522849899016)), ('grand', np.float64(0.016156587303829798)), ('jour', np.float64(0.015510207726903716)), ('nuit', np.float64(0.01539471380886963)), ('femme', np.float64(0.014614202626418731)), ('oeil', np.float64(0.014572561702844123))]

TOPIC 12
[('bon', np.float64(0.019315491958222655)), ('petit', np.float64(0.018568832287211515)), ('grand', np.float64(0.016950323016086722)), ('homme', np.float64(0.016351574097377614)), ('femme', np.float64(0.015541348635530902)), ('air', np.float64(0.01531414757039489)), ('tête', np.float64(0.01445264564797925)), ('mère', np.float64(0.014444469655752646)), ('enfant', np.float64(0.013703377846767477)), ('oeil', np.float64(0.013641430223070568))]

TOPIC 13
[('enfant', np.float64(0.02292181578251993)), ('main', np.float64(0.01805920075980842)), ('cœur', np.float64(0.017696190368347676)), ('femme', np.float64(0.01585785281200622)), ('pauvre', np.float64(0.015796342093574736)), ('petit', np.float64(0.01568293112486041)), ('voix', np.float64(0.015648819891746525)), ('larme', np.float64(0.015293154487186905)), ('grand', np.float64(0.014860298006713247)), ('bon', np.float64(0.014229900174747892))]