# **Import des modules nécessaires**

In [ ]:
import pandas as pd #pour la manipulation de données
from pathlib import Path #pour la gestion des chemins de fichiers
import spacy #pour le prétraitement de texte

from bertopic import BERTopic #pour la modélisation de sujets

from umap import UMAP #pour la réduction de dimensionnalité
from hdbscan import HDBSCAN #pour le clustering de BERTopic

from sklearn.feature_extraction.text import CountVectorizer #pour la vectorisation de texte
from bertopic.vectorizers import ClassTfidfTransformer #pour la vectorisation de texte spécifique à BERTopic

from sentence_transformers import SentenceTransformer #pour les embeddings de phrases

# **Chargement du corpus de Zola et de spacy**

In [48]:
df=pd.read_csv(Path("..") /"data" /"2_processed"/ "02_corpus_zola.csv", encoding="utf-8",)
df.head()

,roman,annee,ordre_romans,paquet_id,texte,nb_mots
0,1865 La confession de Claude.,1865,1,1,"Voici l’hiver: l’air, au matin, devient plus f...",401
1,1865 La confession de Claude.,1865,1,2,Le grillon chantait; le souffle harmonieux des...,336
2,1865 La confession de Claude.,1865,1,3,"Pars cependant, puisque tu as soif de la vie. ...",248
3,1865 La confession de Claude.,1865,1,4,"Ai-je eu trop de confiance en ma force, ma pla...",336
4,1865 La confession de Claude.,1865,1,5,Le premier rayon a chassé le cauchemar de ma v...,359

In [67]:
nlp = spacy.load("fr_core_news_lg") #chargement du modèle de langue français de spacy

nlp.max_length = 2_000_000

In [49]:
df.shape

(10638, 6)

# **Traitement du Corpus de Zola**

In [68]:
def clean_for_topics(text):
    doc = nlp(text)
    mots_propres = []
    
    for token in doc:
        # Exclusion de la ponctuation, des stop words, des nombres et des Entités Nommées
        if token.is_punct or token.is_stop or token.like_num or token.ent_type_ in ['PER', 'LOC', 'ORG']:
            continue
            
        # Conservation et lemmatisation des Noms, Adjectifs et Verbes
        if token.pos_ in ['NOUN', 'ADJ', 'VERB']:
            mots_propres.append(token.lemma_.lower())
            
    return " ".join(mots_propres)

# Application sur ton dataframe existant
print("Nettoyage en cours pour la représentation des topics...")
df['texte_nettoye'] = df['texte'].apply(clean_for_topics)
df.head()

Nettoyage en cours pour la représentation des topics...

,roman,annee,ordre_romans,paquet_id,texte,nb_mots,topic,texte_nettoye
0,1865 La confession de Claude.,1865,1,1,"Voici l’hiver: l’air, au matin, devient plus f...",401,-1,hiver air matin devenir frais mettre manteau b...
1,1865 La confession de Claude.,1865,1,2,Le grillon chantait; le souffle harmonieux des...,336,-1,grillon chanter souffle harmonieux nuit bercer...
2,1865 La confession de Claude.,1865,1,3,"Pars cependant, puisque tu as soif de la vie. ...",248,-1,soif vie projet soi ferme loyal action rêve vi...
3,1865 La confession de Claude.,1865,1,4,"Ai-je eu trop de confiance en ma force, ma pla...",336,136,confiance force place rêver côté jour naître p...
4,1865 La confession de Claude.,1865,1,5,Le premier rayon a chassé le cauchemar de ma v...,359,136,rayon chasser cauchemar veille obstacle accept...

## **1) Choix du modèle d'embedding**

Ici je vais choisir un modèle d'embedding pré-entraîné pour transformer les textes en vecteurs numériques. Je vais utiliser un modèle de la bibliothèque Sentence Transformers, qui est compatible avec BERTopic.

In [64]:
embedding_model = SentenceTransformer(
    "dangvantuan/sentence-camembert-base"
)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/123 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/4.27k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/727 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/443M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/463 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/811k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.40M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/298 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [65]:
print("Génération des embeddings sémantiques...")
embeddings = embedding_model.encode(df['texte'].tolist(), show_progress_bar=True)

Génération des embeddings sémantiques...

Batches:   0%|          | 0/333 [00:00<?, ?it/s]

## **2) Pipeline de Traitement**

In [51]:
docs = df["texte"].tolist()

timestamps = df["ordre_romans"].tolist()

### 1) HDBSCAN

In [85]:
hdbscan_model = HDBSCAN(
    min_cluster_size=15,
    min_samples=1,
    metric='euclidean',
    cluster_selection_method='eom',
    prediction_data=True
)

### 2) UMAP

In [83]:
umap_model = UMAP(
    n_neighbors=15,
    n_components=15,
    min_dist=0.1,
    metric="cosine",
    random_state=42
)

### 2) HDBSCAN

### 3) creation des stop words + vectorisation TF-IDF

In [71]:
stop_word = [
    # noms familiaux centraux
    "rougon", "macquart", "saccard", "mouret", "lantier", "coupeau", "maheu", "fouan", "quenu", "chanteau", "josserand", "deberle",
    "raquin", "lorilleux", "buteau", "roubaud", "baudu", "gervaise",

    # Prénoms / personnages très fréquents
    "pierre", "jean", "jacques", "marie", "madeleine", "pauline", "hélène", "jeanne", "claude", "marius", "lazare", "guillaume",
    "laurent", "philippe", "thérèse", "albine", "maurice", "marthe", "maxime", "daniel", "camille", "serge", "octave", "florent",
    "félicité", "louise", "silvère", "caroline", "lisa", "laurence", "miette", "simon", "josine", "clotilde", "véronique", "juliette",
    "rosalie", "mathieu", "charles", "françoise", "lise", "séverine", "henriette", "georges", "angélique", "adèle", "pascal", "lucie", 
    "martine", "virginie", "suzanne", "valentine", "olympe", "lucien", "armande", "constance", "berthe", "sidonie", "benedetta",

    # prénom / personnages complémentaires
    "luc", "geneviève", "catherine", "chaval", "adélaïde", "antoine", "auguste", "marianne", "clorinde", "normande", "saget", "mlle saget",
    "delhomme", "ragu", "trouche", "sandoz", "mahoudeau", "bonneville", "rastoil", "rambaud", "fenil", "surin", "malignon", "faloise",
    "lambesc", "mignot", "baugé", "morange", "bouchard", "teuse", "pâquerette", "paquerette", "duparque", "mme duparque", "guersaint",
    "aurélie", "aurelie", "mme aurélie", "mme aurelie", "lecœur", "lecoeur", "mme lecœur", "mme lecoeur", "granoux", "bourron",
    "lerat", "mme lerat", "duveyrier", "bachelard", "gueulin", "delaherche", "beauclair", "lison", "orlando", "delbos",
    "boisgelin", "fernande", "sébastien", "sebastien", "mazaud", "dubuche", "moreux", "vigneron", "bourrette", "satan",
    "archangias", "férat", "ferat", "barbue", "trouille", "laveuve",

    # Personnages secondaires / noms très discriminants
    "fauchery", "muffat", "bordenave", "zoé", "mignon", "faujas", "mathéus", "trublot", "fagerolles", "cazalis", "poizat", "jordan",
    "vandeuvres", "condamin", "paloque", "charbonnel", "gilquin", "marjolin", "campardon", "toussaint", "grivet", "denizet", "kahn",
    "hutin", "bonnaire", "laboque", "marsy", "nanet", "favier", "deloche", "goujet", "cadine", "chouteau", "rochas", "lepailleur",
    "séguin", "gagnière", "hourdequin", "macqueron", "théodose", "savin", "gérard", "larsonneau", "morfain", "lorin", "salvat",
    "boche", "gavard", "martelly",

    # Groupes nominaux religieux / institutionnels
    "sœur hyacinthe", "soeur hyacinthe", "mère chantemesse", "mere chantemesse",

     # Formes d’adresse / famille
    "monsieur", "madame", "mademoiselle", "mme", "mlle",
    "maman", "papa", "père", "pere", "mère", "mere",
    "frère", "frere", "frères", "freres", "sœur", "soeur",
    "sœurette", "soeurette", "tante", "oncle", "cousin",
    "cousine", "époux", "epoux", "épouse", "epouse",
    "nièce", "niece",

    # Mots très fréquents et peu informatifs
    "le", "la", "les", "un", "une", "des", "du", "de", "d", "au", "aux",
    "ce", "cet", "cette", "ces", "son", "sa", "ses", "leur", "leurs",
    "je", "tu", "il", "elle", "nous", "vous", "ils", "elles",
    "me", "te", "se", "moi", "toi", "lui", "eux",
    "que", "qui", "quoi", "dont", "où", "et", "ou", "mais", "donc",
    "or", "ni", "car", "ne", "pas", "plus", "moins", "très",
    "dans", "sur", "sous", "avec", "sans", "pour", "par", "comme",
    "chez", "vers", "entre", "contre", "depuis", "pendant",
    "tout", "tous", "toute", "toutes", "même", "autre", "autres",
    "être", "avoir", "faire", "dire", "aller", "voir", "savoir",
    "pouvoir", "vouloir", "falloir", "devoir", "venir", "prendre",
    "mettre", "donner", "trouver", "passer", "rester", "sembler",
    "encore", "toujours", "jamais", "bien", "mal", "peu", "assez",
    "alors", "puis", "enfin", "aussi", "ainsi", "déjà", "là",
    "ici", "cela", "ça", "ceci", "celui", "celle", "ceux", "celles"
]

In [72]:
vectorizer_model = CountVectorizer(
    stop_words=stop_word,
    min_df=5, #
    max_df=0.50 #   
)

ctfidf_model = ClassTfidfTransformer(
    reduce_frequent_words=True
)

### 4) Création du modèle BERTopic

In [86]:
topic_model = BERTopic(
    language="french",
    hdbscan_model=hdbscan_model,
    vectorizer_model=vectorizer_model,
    calculate_probabilities=False,
    verbose=True
)
topics, probs = topic_model.fit_transform(df["texte_nettoye"].tolist(), embeddings= embeddings)

2026-06-03 11:22:09,381 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2026-06-03 11:22:11,555 - BERTopic - Dimensionality - Completed ✓
2026-06-03 11:22:11,556 - BERTopic - Cluster - Start clustering the reduced embeddings
2026-06-03 11:22:12,070 - BERTopic - Cluster - Completed ✓
2026-06-03 11:22:12,076 - BERTopic - Representation - Fine-tuning topics using representation models.
2026-06-03 11:22:12,978 - BERTopic - Representation - Completed ✓

## **3) Topics Présent**

In [87]:
topic_info = topic_model.get_topic_info()
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,5147,-1_tableau_député_ministre_gendarme,"[tableau, député, ministre, gendarme, planche,...",[arrêter regret fils traverser angoisse jour t...
1,0,340,0_volupté_affection_solitude_tiède,"[volupté, affection, solitude, tiède, étreinte...",[fond dévorer impatience raidir tendre nerf vi...
2,1,302,1_écoute_étreinte_sanglot_laisse,"[écoute, étreinte, sanglot, laisse, chéri, veu...",[être rester vouloir vouloir savoir expliquer ...
3,2,239,2_science_social_humanité_pape,"[science, social, humanité, pape, universel, c...",[doute torturer rajeunissement antique catholi...
4,3,201,3_oreiller_couverture_bougie_clef,"[oreiller, couverture, bougie, clef, tiroir, s...",[maman reprendre donner chaise long lit bête e...
...,...,...,...,...,...
132,131,15,131_brigadier_majesté_ministre_notaire,"[brigadier, majesté, ministre, notaire, sabre,...",[-vou remettre particulier pied attendre répon...
133,132,15,132_plume_panier_art_cave,"[plume, panier, art, cave, moineau, raisin, pa...",[poule coq coucher côté bel innocence emplir g...
134,133,15,133_battoir_comtesse_baquet_seau,"[battoir, comtesse, baquet, seau, colique, alc...",[déraisonnable ignoble mettre état pareil hont...
135,134,15,134_libéral_hypothéquer_erreur_bongard,"[libéral, hypothéquer, erreur, bongard, cercle...",[falloir répondre bon déclarer air tranquille ...
136,135,15,135_fagot_maquereau_marmite_ragoût,"[fagot, maquereau, marmite, ragoût, cuiller, h...",[avoir sourire esprit enfant ravir répondre pr...

In [89]:
# Récupération de la dimension temporelle
timestamps = df['annee'].tolist()

# Génération des topics dans le temps
topics_over_time = topic_model.topics_over_time(
    df['texte_nettoye'].tolist(), 
    timestamps, 
    nr_bins=20 # Optionnel : à ajuster selon le nombre d'années distinctes de ton corpus
)

# Visualisation interactive de l'évolution des 10 premiers topics
topic_model.visualize_topics_over_time(topics_over_time, top_n_topics=10)

19it [00:03,  6.30it/s]

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hoverinfo': 'text',
              'hovertext': [<b>Topic 0</b><br>Words: mission, dévouement,
                            solitude, affection, tâche, <b>Topic 0</b><br>Words:
                            nerf, noiraud, volupté, affection, effroi, <b>Topic
                            0</b><br>Words: calèche, volupté, tant, complice,
                            langueur, <b>Topic 0</b><br>Words: pêche, groseille,
                            cerise, poire, trapu, <b>Topic 0</b><br>Words: lis,
                            cueillir, prairie, chat, canard, <b>Topic
                            0</b><br>Words: tousser, deberl, bouillotte, anxiété,
                            anéantissement, <b>Topic 0</b><br>Words: catin, odieux,
                            landau, restaurant, engueuler, <b>Topic 0</b><br>Words:
                            réconciliation, mardi, répugnance, cuisinière, dépaysé,
                            <b>Topic 0</b><br>Words: affection, bougie, fiévreux,
                            maladie, volet, <b>Topic 0</b><br>Words: chandelle,
                            sorbier, goyot, échelon, fosse, <b>Topic
                            0</b><br>Words: peinture, pont, camaraderie, flèche,
                            avenue, <b>Topic 0</b><br>Words: monseigneur,
                            cathédrale, aiguille, péché, serment, <b>Topic
                            0</b><br>Words: tunnel, meurtre, banque, haie, tiède,
                            <b>Topic 0</b><br>Words: dossier, hérédité, psyché,
                            apen, pendule, <b>Topic 0</b><br>Words: maladie,
                            guérie, bouillon, adorable, seigneur, <b>Topic
                            0</b><br>Words: soif, ambassade, surhumain, messe,
                            vertige, <b>Topic 0</b><br>Words: maternité, opération,
                            solitude, opérer, empoisonner, <b>Topic 0</b><br>Words:
                            couple, halle, allégresse, âgé, roche, <b>Topic
                            0</b><br>Words: servage, ajourner, conformer,
                            sensualité, culte],
              'marker': {'color': '#E69F00'},
              'mode': 'lines',
              'name': '0_volupté_affection_solitude_tiède',
              'type': 'scatter',
              'x': {'bdata': ('AiuHFtkjnUCamZmZmSudQM3MzMzMOp' ... 'MzM6WdQM3MzMzMrJ1AZmZmZma0nUA='),
                    'dtype': 'f8'},
              'y': {'bdata': 'FFAQAg0YBAIaBhMSGBQPBRURCA==', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 1</b><br>Words: mourant, apaisement, infâme,
                            cruel, infamie, <b>Topic 1</b><br>Words: étreinte,
                            cruel, bohémien, passé, lâcheté, <b>Topic
                            1</b><br>Words: tant, coupé, étreinte, moulin, tocsin,
                            <b>Topic 1</b><br>Words: resserre, supposer, poule,
                            héritage, légume, <b>Topic 1</b><br>Words: écoute,
                            parterre, parfum, feuillage, alcôve, <b>Topic
                            1</b><br>Words: baisa, bouché, content, sanglot,
                            ronfler, <b>Topic 1</b><br>Words: diamant, ronflement,
                            partage, accouder, écoute, <b>Topic 1</b><br>Words:
                            rater, paroissien, gaz, marié, gifle, <b>Topic
                            1</b><br>Words: veu, étreinte, angine, toux,
                            fanfaronnade, <b>Topic 1</b><br>Words: injustice,
                            écoute, cage, maheude, brocanteur, <b>Topic
                            1</b><br>Words: tableau, peinture, échelle, maudire,
                            pose, <b>Topic 1</b><br>Words: punition, soumettre,
                            empourprer, vitrail, broderie, <b>Topic 1</b><br>Words:
                            chéri, écoute, embrasse, bague, oubli, <b>Topic
                            1</b><br>Words: renvoyer, chéri, écoute, tai, étreinte,
                            <b>Topic 1</b><br>Words: prescience, secours,
                            égarement, agenouiller, massue, <b>Topic
                            1</b><br>Words: vien, décor, patrie, population,
                            laisse, <b>Topic 1</b><br>Words: étreinte, chéri,
                            tâche, veu, néant, <b>Topic 1</b><br>Words: étreinte,
                            écoute, abîme, sacrifice, immonde, <b>Topic
                            1</b><br>Words: poison, erreur, petite, rupture,
                            torturer],
              'marker': {'color': '#56B4E9'},
              'mode': 'lines',
              'name': '1_écoute_étreinte_sanglot_laisse',
              'type': 'scatter',
              'x': {'bdata': ('AiuHFtkjnUCamZmZmSudQM3MzMzMOp' ... 'MzM6WdQM3MzMzMrJ1AZmZmZma0nUA='),
                    'dtype': 'f8'},
              'y': {'bdata': 'HycNBSQHBAkQBQwHDBgBBCEOHg==', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 2</b><br>Words: poète, fée, opposition,
                            liberté, discours, <b>Topic 2</b><br>Words:
                            conservateur, journalisme, corporation, élément,
                            négociant, <b>Topic 2</b><br>Words: aspiration,
                            liberté, volume, situer, république, <b>Topic
                            2</b><br>Words: tribune, parlement, rapporteur,
                            suffrage, prêtrise, <b>Topic 2</b><br>Words: thèse,
                            juvénile, maturité, déraisonnable, pessimisme, <b>Topic
                            2</b><br>Words: maheude, coron, grève, fosse, mineur,
                            <b>Topic 2</b><br>Words: impôt, roi, seigneur, famine,
                            propriété, <b>Topic 2</b><br>Words: capital,
                            spéculation, cité, humanité, toux, <b>Topic
                            2</b><br>Words: sein, humanité, science, piqûre, cité,
                            <b>Topic 2</b><br>Words: guérison, science, certificat,
                            constater, divin, <b>Topic 2</b><br>Words: pape,
                            science, catholique, catholicisme, socialisme, <b>Topic
                            2</b><br>Words: science, social, loi, universel,
                            catholicisme, <b>Topic 2</b><br>Words: salariat,
                            social, humanité, richesse, association, <b>Topic
                            2</b><br>Words: instituteur, enseignement, primaire,
                            classe, élève],
              'marker': {'color': '#009E73'},
              'mode': 'lines',
              'name': '2_science_social_humanité_pape',
              'type': 'scatter',
              'x': {'bdata': ('AiuHFtkjnUCamZmZmSudQM3MzMzMOp' ... 'MzpZ1AzczMzMysnUBmZmZmZrSdQA=='),
                    'dtype': 'f8'},
              'y': {'bdata': 'AgMDAwEICAoIGioiMCs=', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 3</b><br>Words: orphelin, lycée, délacer,
                            embarrassant, adoptif, <b>Topic 3</b><br>Words:
                            cabriolet, clef, anxiété, nourrice, couverture,
                            <b>Topic 3</b><br>Words: aiguille, lunette, tricoter,
                            pupitre, tant, <b>Topic 3</b><br>Words: terrasse, clef,
                            oreiller, déménagement, piquet, <b>Topic
                            3</b><br>Words: colonel, boudoir, comtesse, duvet,
                            délire, <b>Topic 3</b><br>Words: couverture, oreiller,
                            châle, chéri, accès, <b>Topic 3</b><br>Words: comtesse,
                            valse, oreiller, tenture, siège, <b>Topic
                            3</b><br>Words: conjugal, corset, cordon, empoigner,
                            délacer, <b>Topic 3</b><br>Words: accouchée, corridor,
                            bougie, oreiller, maladie, <b>Topic 3</b><br>Words:
                            chocolat, brioche, ronflement, reproche, attrape,
                            <b>Topic 3</b><br>Words: oreiller, matelas, sursaut,
                            bougie, hurler, <b>Topic 3</b><br>Words: col, guimpe,
                            manchette, bourrasque, ortie, <b>Topic 3</b><br>Words:
                            montre, dévêtir, bougie, voleur, clef, <b>Topic
                            3</b><br>Words: oreiller, bijou, clef, tiroir, dossier,
                            <b>Topic 3</b><br>Words: guérie, guérison, directrice,
                            matelas, procession, <b>Topic 3</b><br>Words: couvent,
                            laisse, candide, oreiller, cloison, <b>Topic
                            3</b><br>Words: démence, rectitude, salarié, lien,
                            alangui, <b>Topic 3</b><br>Words: volet, rôdeur,
                            verrou, modèle, bougie],
              'marker': {'color': '#F0E442'},
              'mode': 'lines',
              'name': '3_oreiller_couverture_bougie_clef',
              'type': 'scatter',
              'x': {'bdata': ('AiuHFtkjnUCamZmZmSudQM3MzMzMOp' ... 'MzMzOlnUDNzMzMzKydQGZmZmZmtJ1A'),
                    'dtype': 'f8'},
              'y': {'bdata': 'AhYGFgcoBwUfAxMBBwkHBgIF', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 4</b><br>Words: boudin, charcutier,
                            charcuterie, marmite, saucisse, <b>Topic
                            4</b><br>Words: assiette, escabeau, soupe, servant,
                            olivier, <b>Topic 4</b><br>Words: zingueur, chapelier,
                            blanchisseur, litre, assiette, <b>Topic 4</b><br>Words:
                            vertu, rôti, boulevard, calotte, style, <b>Topic
                            4</b><br>Words: éplucher, ridicule, fiche, charbonnier,
                            gigot, <b>Topic 4</b><br>Words: symphonie, subvention,
                            préfet, direction, tiroir, <b>Topic 4</b><br>Words:
                            maheude, fromage, pomme, soupe, mineur, <b>Topic
                            4</b><br>Words: litre, soûl, viande, oie, vigne,
                            <b>Topic 4</b><br>Words: cathédrale, légende, repousse,
                            gouverneur, églantier, <b>Topic 4</b><br>Words:
                            logement, buraliste, veuf, chauffeur, fromage, <b>Topic
                            4</b><br>Words: escouade, gamelle, oie, ficelle,
                            portion, <b>Topic 4</b><br>Words: nourrice, chlorose,
                            trois, nourricier, dandinement, <b>Topic
                            4</b><br>Words: lacer, maraudeur, antre, agile,
                            épicerie],
              'marker': {'color': '#D55E00'},
              'mode': 'lines',
              'name': '4_zingueur_assiette_litre_chapelier',
              'type': 'scatter',
              'x': {'bdata': ('ZmZmZmZCnUAAAAAAAEqdQJqZmZmZUZ' ... 'ZmZo6dQDMzMzMzpZ1AzczMzMysnUA='),
                    'dtype': 'f8'},
              'y': {'bdata': 'CwRYBQYICBABAgQBAQ==', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 5</b><br>Words: union, souiller, dision,
                            tutoyant, causeur, <b>Topic 5</b><br>Words: tai,
                            portefaix, infamie, charron, mercier, <b>Topic
                            5</b><br>Words: cigare, bal, perron, belle, mondaine,
                            <b>Topic 5</b><br>Words: charcutier, écharpe, gardien,
                            architecte, pot, <b>Topic 5</b><br>Words: cabriolet,
                            fétide, balbutia, malhonnête, terrine, <b>Topic
                            5</b><br>Words: pan, louchon, anisette, battoir,
                            zingueur, <b>Topic 5</b><br>Words: toquade, vipère,
                            sole, gentillesse, saler, <b>Topic 5</b><br>Words:
                            embêtement, carton, enlaidir, aplati, chéri, <b>Topic
                            5</b><br>Words: timbale, signifier, exploitation,
                            récompenser, appareil, <b>Topic 5</b><br>Words:
                            deneulin, pierronne, grisou, galant, renvoyer, <b>Topic
                            5</b><br>Words: men, fiche, raidie, vacher, blé,
                            <b>Topic 5</b><br>Words: tant, drogue, flore, garce,
                            caser, <b>Topic 5</b><br>Words: landau, juin,
                            broussaille, écoute, dangereux, <b>Topic
                            5</b><br>Words: men, reprocher, reproche, caprice,
                            élevé, <b>Topic 5</b><br>Words: clé, saute, ébouriffé,
                            saleté, écoute, <b>Topic 5</b><br>Words: désapprouver,
                            instituteur, pense, chéri, exception],
              'marker': {'color': '#0072B2'},
              'mode': 'lines',
              'name': '5_men_clé_pan_écoute',
              'type': 'scatter',
              'x': {'bdata': ('AiuHFtkjnUCamZmZmSudQM3MzMzMOp' ... 'MzM6WdQM3MzMzMrJ1AZmZmZma0nUA='),
                    'dtype': 'f8'},
              'y': {'bdata': 'AgoJCwkNDwQIBQ4MBwcICg==', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 6</b><br>Words: plaine, étouffant, vallon,
                            aspect, âcre, <b>Topic 6</b><br>Words: dalle, vitrage,
                            creuser, vitre, cuivré, <b>Topic 6</b><br>Words:
                            muraille, esplanade, rampe, façade, toit, <b>Topic
                            6</b><br>Words: pavillon, marée, camion, beurre,
                            toiture, <b>Topic 6</b><br>Words: nef, branche, quai,
                            vallée, colline, <b>Topic 6</b><br>Words: rive, nuage,
                            toiture, fleuve, façade, <b>Topic 6</b><br>Words:
                            satin, reine, guérite, mât, poteau, <b>Topic
                            6</b><br>Words: étoffe, bannière, galerie, suspendre,
                            calicot, <b>Topic 6</b><br>Words: canal, marais, rase,
                            houille, plaine, <b>Topic 6</b><br>Words: quai,
                            coupole, arche, boule, rive, <b>Topic 6</b><br>Words:
                            monseigneur, abside, monstre, grille, évêché, <b>Topic
                            6</b><br>Words: cube, drapeau, vendredi, hérisser,
                            aperçu, <b>Topic 6</b><br>Words: aire, pont, incendier,
                            berge, colonne, <b>Topic 6</b><br>Words: bannière, nef,
                            cierge, colline, travée, <b>Topic 6</b><br>Words:
                            palais, façade, fleuve, dôme, portique, <b>Topic
                            6</b><br>Words: galoper, avenue, carrefour, esplanade,
                            frauder, <b>Topic 6</b><br>Words: câble, jet,
                            étincelle, halle, bluet, <b>Topic 6</b><br>Words:
                            aristocratique, idole, drapeau, palpitant, domaine],
              'marker': {'color': '#CC79A7'},
              'mode': 'lines',
              'name': '6_toiture_façade_quai_palais',
              'type': 'scatter',
              'x': {'bdata': ('AiuHFtkjnUCamZmZmSudQM3MzMzMOp' ... 'MzMzOlnUDNzMzMzKydQGZmZmZmtJ1A'),
                    'dtype': 'f8'},
              'y': {'bdata': 'AgULBwoLAwYEAwQCDAkYBQQB', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 7</b><br>Words: adorable, chiffrer, effraya,
                            emplette, raillerie, <b>Topic 7</b><br>Words: armateur,
                            remboursement, évasion, ceinture, acquitter, <b>Topic
                            7</b><br>Words: bijou, aigrette, mairie, prix, dette,
                            <b>Topic 7</b><br>Words: poissonnière, sole, locataire,
                            cuisinière, poire, <b>Topic 7</b><br>Words: malle,
                            paillette, chasuble, lapin, convoi, <b>Topic
                            7</b><br>Words: forgeron, seau, contrarier, répondit,
                            baquet, <b>Topic 7</b><br>Words: pouliche, balayage,
                            louis, pesage, bookmaker, <b>Topic 7</b><br>Words:
                            crin, fichu, verrou, bœuf, doter, <b>Topic
                            7</b><br>Words: bonsoir, secrétaire, dépouiller,
                            préoccuper, calcul, <b>Topic 7</b><br>Words: terri,
                            hiérarchique, recoller, fiche, bêcher, <b>Topic
                            7</b><br>Words: tableau, talent, décoller, modèle,
                            poêle, <b>Topic 7</b><br>Words: baissier, confiance,
                            joueur, utile, embarras, <b>Topic 7</b><br>Words:
                            blessa, économie, jetât, éplucher, stupéfier, <b>Topic
                            7</b><br>Words: affligé, consolée, nauséabond, étouffé,
                            arrachement, <b>Topic 7</b><br>Words: bagage, demie,
                            reverdir, desserte, incroyant, <b>Topic 7</b><br>Words:
                            enceint, cuisinière, prison, meneur, terroriser,
                            <b>Topic 7</b><br>Words: automobile, stupide,
                            émotionnait, confidence, nostalgie, <b>Topic
                            7</b><br>Words: instituteur, secourir, pénitent,
                            catholique, connaissance],
              'marker': {'color': '#E69F00'},
              'mode': 'lines',
              'name': '7_moquer_billet_confiance_contrarier',
              'type': 'scatter',
              'x': {'bdata': ('AiuHFtkjnUCamZmZmSudQM3MzMzMOp' ... 'MzMzOlnUDNzMzMzKydQGZmZmZmtJ1A'),
                    'dtype': 'f8'},
              'y': {'bdata': 'BAcKCgkIAgoHAgoKAQIBDQQF', 'dtype': 'i1'}},
             {'hoverinfo': 'text',
              'hovertext': [<b>Topic 8</b><br>Words: notaire, armateur,
                            paroissien, propriétaire, portefaix, <b>Topic
                            8</b><br>Words: divan, véhément, larmoyer, moelleux,
                            entonner, <b>Topic 8</b><br>Words: vicaire, préfet,
                            évêque, préfecture, diocèse, <b>Topic 8</b><br>Words:
                            démission, tuile, curer, sécher, cardinal, <b>Topic
                            8</b><br>Words: omnibus, dispenser, détendu,
                            inextricable, griller, <b>Topic 8</b><br>Words: boule,
                            prospectus, minouche, affaibli, griffe, <b>Topic
                            8</b><br>Words: grève, régisseur, dessert, copieux,
                            atterrer, <b>Topic 8</b><br>Words: simplicité, palette,
                            chevalet, infect, parrain, <b>Topic 8</b><br>Words:
                            article, numéro, probité, publier, spécial, <b>Topic
                            8</b><br>Words: pèlerin, hospitalier, hôtelier, loger,
                            vicaire, <b>Topic 8</b><br>Words: cardinal, vicomte,
                            jésuite, soutane, pèlerinage, <b>Topic 8</b><br>Words:
                            admission, asile, professorat, baron, séance, <b>Topic
                            8</b><br>Words: palier, labyrinthe, grimpant, rentre,
                            fourneau, <b>Topic 8</b><br>Words: programme, classe,
                            indiscipliné, inspecteur, sagesse],
              'marker': {'color': '#56B4E9'},
              'mode': 'lines',
              'name': '8_cardinal_vicaire_soutane_évêque',
              'type': 'scatter',
              'x': {'bdata': ('mpmZmZkrnUDNzMzMzDqdQGZmZmZmQp' ... 'MzpZ1AzczMzMysnUBmZmZmZrSdQA=='),

In [88]:
for topic_id in topic_info["Topic"].head(15):
    if topic_id != -1:
        print("\nTOPIC", topic_id)
        print(topic_model.get_topic(topic_id)[:15])

TOPIC 0
[('volupté', np.float64(0.007313906920985119)), ('affection', np.float64(0.007283256832130206)), ('solitude', np.float64(0.006521384957157691)), ('tiède', np.float64(0.0062819219839529705)), ('étreinte', np.float64(0.005528118763126145)), ('meurtre', np.float64(0.005298741041785427)), ('passé', np.float64(0.005292815339306285)), ('nerf', np.float64(0.005128924277715361)), ('déchirer', np.float64(0.004966210367856219)), ('maladie', np.float64(0.004680271390563365))]

TOPIC 1
[('écoute', np.float64(0.012314660466352295)), ('étreinte', np.float64(0.012289235743916431)), ('sanglot', np.float64(0.009505847921192457)), ('laisse', np.float64(0.008842439833508398)), ('chéri', np.float64(0.00857232506737913)), ('veu', np.float64(0.008226589977665233)), ('tai', np.float64(0.006960521891359497)), ('cruel', np.float64(0.006544827037940918)), ('affection', np.float64(0.006167992371452063)), ('poison', np.float64(0.006109693370025943))]

TOPIC 2
[('science', np.float64(0.01313649963164348)), ('social', np.float64(0.01135418773171396)), ('humanité', np.float64(0.010711270987947042)), ('pape', np.float64(0.00949340321619661)), ('universel', np.float64(0.00928284257737844)), ('catholicisme', np.float64(0.00911620052344372)), ('nation', np.float64(0.009054010421618318)), ('loi', np.float64(0.008251548406058106)), ('catholique', np.float64(0.008188859845402553)), ('erreur', np.float64(0.007318739520105517))]

TOPIC 3
[('oreiller', np.float64(0.014455373064439024)), ('couverture', np.float64(0.012390319769519164)), ('bougie', np.float64(0.011165926735923171)), ('clef', np.float64(0.010130327538883883)), ('tiroir', np.float64(0.007702722414845242)), ('sanglot', np.float64(0.007114311334169937)), ('chéri', np.float64(0.006548387175116223)), ('maladie', np.float64(0.00627183926877311)), ('guérie', np.float64(0.005802966135030223)), ('accouchée', np.float64(0.005772412554979582))]

TOPIC 4
[('zingueur', np.float64(0.016090070445302408)), ('assiette', np.float64(0.012096719701377549)), ('litre', np.float64(0.011851208461777596)), ('chapelier', np.float64(0.011078630143462227)), ('viande', np.float64(0.010722610954622245)), ('blanchisseur', np.float64(0.010675387268215016)), ('marmite', np.float64(0.010392962890354471)), ('oie', np.float64(0.010237758997079942)), ('pincer', np.float64(0.009523670581180723)), ('avaler', np.float64(0.00909515348533892))]

TOPIC 5
[('men', np.float64(0.011564615690788852)), ('clé', np.float64(0.010498085059402102)), ('pan', np.float64(0.010356131184635648)), ('écoute', np.float64(0.00788582336521163)), ('veu', np.float64(0.007308547102983474)), ('salir', np.float64(0.006725920500902168)), ('galant', np.float64(0.006668656017576647)), ('instituteur', np.float64(0.006649677702141554)), ('fiche', np.float64(0.006549329692458122)), ('tape', np.float64(0.006474989172823963))]

TOPIC 6
[('toiture', np.float64(0.009628412990744985)), ('façade', np.float64(0.009343273629332866)), ('quai', np.float64(0.00856352150874957)), ('palais', np.float64(0.008303458736203154)), ('muraille', np.float64(0.008088424215524474)), ('étoile', np.float64(0.007549863647306773)), ('nef', np.float64(0.007497717754620772)), ('pont', np.float64(0.007475118623665655)), ('fleuve', np.float64(0.007234951526738387)), ('construction', np.float64(0.007068214171856601))]

TOPIC 7
[('moquer', np.float64(0.008005686063151768)), ('billet', np.float64(0.007889141232928436)), ('confiance', np.float64(0.00782469934530435)), ('contrarier', np.float64(0.0077742556961499345)), ('cuisinière', np.float64(0.007109244611772761)), ('vilain', np.float64(0.0069643217213873785)), ('embarras', np.float64(0.006886406655441053)), ('sottise', np.float64(0.00657475588972608)), ('locataire', np.float64(0.006354310701139648)), ('menteur', np.float64(0.0063215030009615624))]

TOPIC 8
[('cardinal', np.float64(0.01605777890114443)), ('vicaire', np.float64(0.01579639523166472)), ('soutane', np.float64(0.013142840356168875)), ('évêque', np.float64(0.012670685990880354)), ('préfet', np.float64(0.011149434628369034)), ('notaire', np.float64(0.0090357027448661)), ('diocèse', np.float64(0.00838248912726094)), ('vicomte', np.float64(0.008319865183230284)), ('ministre', np.float64(0.008089026455405242)), ('préfecture', np.float64(0.008040696714214184))]

TOPIC 9
[('cadavre', np.float64(0.01032068276923373)), ('meurtrier', np.float64(0.009309723958165726)), ('contraction', np.float64(0.008614017726924467)), ('sanglot', np.float64(0.008285468433917795)), ('atroce', np.float64(0.008078110867223468)), ('effroi', np.float64(0.007760037353266437)), ('cicatrice', np.float64(0.0075876350724068484)), ('épouvante', np.float64(0.007331519022339353)), ('victime', np.float64(0.00732793843074616)), ('cuisse', np.float64(0.007241813405531087))]

TOPIC 10
[('vendeur', np.float64(0.025623174324781558)), ('confection', np.float64(0.015982506959121102)), ('comptoir', np.float64(0.015868313662776207)), ('étoffe', np.float64(0.0128924484093739)), ('lainage', np.float64(0.01060761308914187)), ('satin', np.float64(0.010475114332616295)), ('manteau', np.float64(0.010338142551711985)), ('étalage', np.float64(0.009609754911509451)), ('vitrine', np.float64(0.009380874177169842)), ('mercerie', np.float64(0.009123255787318279))]

TOPIC 11
[('piano', np.float64(0.012502174200329721)), ('comtesse', np.float64(0.010001916063819047)), ('marquis', np.float64(0.007720797832459212)), ('architecte', np.float64(0.007392009506576905)), ('loge', np.float64(0.0072791435731236745)), ('correct', np.float64(0.007211474470496666)), ('teint', np.float64(0.0071835906767925214)), ('baron', np.float64(0.00675687678290627)), ('rougir', np.float64(0.006721678724927945)), ('enchanter', np.float64(0.006451198496452862))]

TOPIC 12
[('gain', np.float64(0.012277158810752984)), ('spéculation', np.float64(0.011313173051397481)), ('bâtir', np.float64(0.010373919019607346)), ('titre', np.float64(0.010097787947580787)), ('considérable', np.float64(0.009980562416912312)), ('denier', np.float64(0.00945695313495552)), ('chiffre', np.float64(0.009133592016136748)), ('banque', np.float64(0.008947893660916823)), ('bénéfice', np.float64(0.008610362614600237)), ('perte', np.float64(0.008578982386839249))]

TOPIC 13
[('cadavre', np.float64(0.01098453511346877)), ('chou', np.float64(0.008609008102776055)), ('légume', np.float64(0.008375008723326775)), ('agonie', np.float64(0.007744674644556621)), ('carotte', np.float64(0.007535255640602969)), ('cauchemar', np.float64(0.007152583988556097)), ('prisonnier', np.float64(0.006942679463860274)), ('sac', np.float64(0.006926322997233097)), ('bûcher', np.float64(0.006727971509030022)), ('paillasse', np.float64(0.006654919039240873))]